<a href="https://colab.research.google.com/github/asadbek11211/Pandas_exsamples/blob/main/SQLite_omboriga_ulanish_amaliyot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SQLite ma'lumotlar ombori bilan ishlash

In [1]:
import pandas as pd
import sqlite3 as sql
from pprint import pprint as print

In [2]:
! wget https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip

--2023-02-14 16:39:01--  https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
Resolving www.sqlitetutorial.net (www.sqlitetutorial.net)... 151.139.128.10
Connecting to www.sqlitetutorial.net (www.sqlitetutorial.net)|151.139.128.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 305596 (298K) [application/zip]
Saving to: ‘chinook.zip’

chinook.zip         100%[===================>] 298.43K  --.-KB/s    in 0.008s

2023-02-14 16:39:01 (37.6 MB/s) - ‘chinook.zip’ saved [305596/305596]

In [3]:
!unzip chinook.zip

Archive:  chinook.zip
  inflating: chinook.db

In [5]:
db = sql.connect("chinook.db")
cursor = db.cursor()

In [6]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
cursor.fetchall()

[('albums',),
 ('sqlite_sequence',),
 ('artists',),
 ('customers',),
 ('employees',),
 ('genres',),
 ('invoices',),
 ('invoice_items',),
 ('media_types',),
 ('playlists',),
 ('playlist_track',),
 ('tracks',),
 ('sqlite_stat1',)]

In [10]:
cursor.execute("SELECT COUNT (*) FROM customers")
cursor.fetchone()

(59,)

In [17]:
cursor.execute("PRAGMA table_info(customers);")
cursor.fetchall()

[(0, 'CustomerId', 'INTEGER', 1, None, 1),
 (1, 'FirstName', 'NVARCHAR(40)', 1, None, 0),
 (2, 'LastName', 'NVARCHAR(20)', 1, None, 0),
 (3, 'Company', 'NVARCHAR(80)', 0, None, 0),
 (4, 'Address', 'NVARCHAR(70)', 0, None, 0),
 (5, 'City', 'NVARCHAR(40)', 0, None, 0),
 (6, 'State', 'NVARCHAR(40)', 0, None, 0),
 (7, 'Country', 'NVARCHAR(40)', 0, None, 0),
 (8, 'PostalCode', 'NVARCHAR(10)', 0, None, 0),
 (9, 'Phone', 'NVARCHAR(24)', 0, None, 0),
 (10, 'Fax', 'NVARCHAR(24)', 0, None, 0),
 (11, 'Email', 'NVARCHAR(60)', 1, None, 0),
 (12, 'SupportRepId', 'INTEGER', 0, None, 0)]

In [18]:
cursor.execute("SELECT COUNT (*) FROM employees")
cursor.fetchone()

(8,)

In [20]:
from sqlite3.dbapi2 import Cursor
cursor.execute("SELECT * FROM customers")
cus = cursor.fetchall()

In [25]:
df = pd.read_sql("SELECT * FROM customers", db, index_col='CustomerId')

In [26]:
df

,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
CustomerId,,,,,,,,,,,,
1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4
6,Helena,Holý,None,Rilská 3174/6,Prague,None,Czech Republic,14300,+420 2 4177 0449,None,hholy@gmail.com,5
7,Astrid,Gruber,None,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,None,Austria,1010,+43 01 5134505,None,astrid.gruber@apple.at,5
8,Daan,Peeters,None,Grétrystraat 63,Brussels,None,Belgium,1000,+32 02 219 03 03,None,daan_peeters@apple.be,4
9,Kara,Nielsen,None,Sønder Boulevard 51,Copenhagen,None,Denmark,1720,+453 3331 9991,None,kara.nielsen@jubii.dk,4
10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4
11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5
12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3
13,Fernanda,Ramos,None,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4
14,Mark,Philips,Telus,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,+1 (780) 434-4554,+1 (780) 434-5565,mphilips12@shaw.ca,5
15,Jennifer,Peterson,Rogers Canada,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,+1 (604) 688-2255,+1 (604) 688-8756,jenniferp@rogers.ca,3
16,Frank,Harris,Google Inc.,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,+1 (650) 253-0000,+1 (650) 253-0000,fharris@google.com,4
17,Jack,Smith,Microsoft Corporation,1 Microsoft Way,Redmond,WA,USA,98052-8300,+1 (425) 882-8080,+1 (425) 882-8081,jacksmith@microsoft.com,5
18,Michelle,Brooks,None,627 Broadway,New York,NY,USA,10012-2612,+1 (212) 221-3546,+1 (212) 221-4679,michelleb@aol.com,3
19,Tim,Goyer,Apple Inc.,1 Infinite Loop,Cupertino,CA,USA,95014,+1 (408) 996-1010,+1 (408) 996-1011,tgoyer@apple.com,3
20,Dan,Miller,None,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,+1 (650) 644-3358,None,dmiller@comcast.com,4
21,Kathy,Chase,None,801 W 4th Street,Reno,NV,USA,89503,+1 (775) 223-7665,None,kachase@hotmail.com,5
22,Heather,Leacock,None,120 S Orange Ave,Orlando,FL,USA,32801,+1 (407) 999-7788,None,hleacock@gmail.com,4
23,John,Gordon,None,69 Salem Street,Boston,MA,USA,2113,+1 (617) 522-1333,None,johngordon22@yahoo.com,4
24,Frank,Ralston,None,162 E Superior Street,Chicago,IL,USA,60611,+1 (312) 332-3232,None,fralston@gmail.com,3
25,Victor,Stevens,None,319 N. Frances Street,Madison,WI,USA,53703,+1 (608) 257-0597,None,vstevens@yahoo.com,5
26,Richard,Cunningham,None,2211 W Berry Street,Fort Worth,TX,USA,76110,+1 (817) 924-7272,None,ricunningham@hotmail.com,4
27,Patrick,Gray,None,1033 N Park Ave,Tucson,AZ,USA,85719,+1 (520) 622-4200,None,patrick.gray@aol.com,4
28,Julia,Barnett,None,302 S 700 E,Salt Lake City,UT,USA,84102,+1 (801) 531-7272,None,jubarnett@gmail.com,5
29,Robert,Brown,None,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,+1 (416) 363-8888,None,robbrown@shaw.ca,3
30,Edward,Francis,None,230 Elgin Street,Ottawa,ON,Canada,K2P 1L7,+1 (613) 234-3322,None,edfrancis@yachoo.ca,3
31,Martha,Silk,None,194A Chain Lake Drive,Halifax,NS,Canada,B3S 1C5,+1 (902) 450-0450,None,marthasilk@gmail.com,5
32,Aaron,Mitchell,None,696 Osborne Street,Winnipeg,MB,Canada,R3L 2B9,+1 (204) 452-6452,None,aaronmitchell@yahoo.ca,4
33,Ellie,Sullivan,None,5112 48 Street,Yellowknife,NT,Canada,X1A 1N6,+1 (867) 920-2233,None,ellie.sullivan@shaw.ca,3
34,João,Fernandes,None,Rua da Assunção 53,Lisbon,None,Portugal,None,+351 (213) 466-111,None,jfernandes@yahoo.pt,4
35,Madalena,Sampaio,None,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,+351 (225) 022-448,None,masampaio@sapo.pt,4
36,Hannah,Schneider,None,Tauentzienstraße 8,Berlin,None,Germany,10789,+49 030 26550280,None,hannah.schneider@yahoo.de,5
37,Fynn,Zimmermann,None,Berger Straße 10,Frankfurt,None,Germany,60316,+49 069 40598889,None,fzimmermann@yahoo.de,3
38,Niklas,Schröder,None,Barbarossastraße 19,Berlin,None,Germany,10779,+49 030 2141444,None,nschroder@surfeu.de,3
39,Camille,Bernard,None,"4, Rue Milton",Paris,None,France,75009,+33 01 49 70 65 65,None,camille.bernard@yahoo.fr,4
40,Dominique,Lefebvre,None,"8, Rue Hanovre",Paris,None,France,75002,+33 01 47 42 71 71,None,dominiquelefebvre@gmail.com,4
41,Marc,Dubois,None,"11, Place Bellecour",Lyon,None,France,69002,+33 04 78 30 30 30,None,marc.dubois@hotmail.com,5
42,Wyatt,Girard,None,"9, Place Louis Barthou",Bordeaux,None,France,33000,+33 05 56 96 96 96,None,wyatt.girard@yahoo.fr,3
43,Isabelle,Mercier,None,"68, Rue Jouvence",Dijon,None,France,21000,+33 03 80 73 66 99,None,isabelle_mercier@apple.fr,3
44,Terhi,Hämäläinen,None,Porthaninkatu 9,Helsinki,None,Finland,00530,+358 09 870 2000,None,terhi.hamalainen@apple.fi,3
45,Ladislav,Kovács,None,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,None,None,ladislav_kovacs@apple.hu,3
46,Hugh,O'Reilly,None,3 Chatham Street,Dublin,Dublin,Ireland,None,+353 01 6792424,None,hughoreilly@apple.ie,3
47,Lucas,Mancini,None,"Via Degli Scipioni, 43",Rome,RM,Italy,00192,+39 06 39733434,None,lucas.mancini@yahoo.it,5
48,Johannes,Van der Berg,None,Lijnbaansgracht 120bg,Amsterdam,VV,Netherlands,1016,+31 020 6223130,None,johavanderberg@yahoo.nl,5
49,Stanisław,Wójcik,None,Ordynacka 10,Warsaw,None,Poland,00-358,+48 22 828 37 39,None,stanisław.wójcik@wp.pl,4
50,Enrique,Muñoz,None,C/ San Bernardo 85,Madrid,None,Spain,28015,+34 914 454 454,None,enrique_munoz@yahoo.es,5
51,Joakim,Johansson,None,Celsiusg. 9,Stockholm,None,Sweden,11230,+46 08-651 52 52,None,joakim.johansson@yahoo.se,5
52,Emma,Jones,None,202 Hoxton Street,London,None,United Kingdom,N1 5LH,+44 020 7707 0707,None,emma_jones@hotmail.com,3
53,Phil,Hughes,None,113 Lupus St,London,None,United Kingdom,SW1V 3EN,+44 020 7976 5722,None,phil.hughes@gmail.com,3
54,Steve,Murray,None,110 Raeburn Pl,Edinburgh,None,United Kingdom,EH4 1HH,+44 0131 315 3300,None,steve.murray@yahoo.uk,5
55,Mark,Taylor,None,421 Bourke Street,Sidney,NSW,Australia,2010,+61 (02) 9332 3633,None,mark.taylor@yahoo.au,4
56,Diego,Gutiérrez,None,307 Macacha Güemes,Buenos Aires,None,Argentina,1106,+54 (0)11 4311 4333,None,diego.gutierrez@yahoo.ar,4
57,Luis,Rojas,None,"Calle Lira, 198",Santiago,None,Chile,None,+56 (0)2 635 4444,None,luisrojas@yahoo.cl,5
58,Manoj,Pareek,None,"12,Community Centre",Delhi,None,India,110017,+91 0124 39883988,None,manoj.pareek@rediff.com,3
59,Puja,Srivastava,None,"3,Raj Bhavan Road",Bangalore,None,India,560001,+91 080 22289999,None,puja_srivastava@yahoo.in,3

In [28]:
pd.read_sql("SELECT * FROM customers LIMIT 20", db, index_col='CustomerId')

,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
CustomerId,,,,,,,,,,,,
1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4
6,Helena,Holý,None,Rilská 3174/6,Prague,None,Czech Republic,14300,+420 2 4177 0449,None,hholy@gmail.com,5
7,Astrid,Gruber,None,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,None,Austria,1010,+43 01 5134505,None,astrid.gruber@apple.at,5
8,Daan,Peeters,None,Grétrystraat 63,Brussels,None,Belgium,1000,+32 02 219 03 03,None,daan_peeters@apple.be,4
9,Kara,Nielsen,None,Sønder Boulevard 51,Copenhagen,None,Denmark,1720,+453 3331 9991,None,kara.nielsen@jubii.dk,4
10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4
11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5
12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3
13,Fernanda,Ramos,None,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4
14,Mark,Philips,Telus,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,+1 (780) 434-4554,+1 (780) 434-5565,mphilips12@shaw.ca,5
15,Jennifer,Peterson,Rogers Canada,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,+1 (604) 688-2255,+1 (604) 688-8756,jenniferp@rogers.ca,3
16,Frank,Harris,Google Inc.,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,+1 (650) 253-0000,+1 (650) 253-0000,fharris@google.com,4
17,Jack,Smith,Microsoft Corporation,1 Microsoft Way,Redmond,WA,USA,98052-8300,+1 (425) 882-8080,+1 (425) 882-8081,jacksmith@microsoft.com,5
18,Michelle,Brooks,None,627 Broadway,New York,NY,USA,10012-2612,+1 (212) 221-3546,+1 (212) 221-4679,michelleb@aol.com,3
19,Tim,Goyer,Apple Inc.,1 Infinite Loop,Cupertino,CA,USA,95014,+1 (408) 996-1010,+1 (408) 996-1011,tgoyer@apple.com,3
20,Dan,Miller,None,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,+1 (650) 644-3358,None,dmiller@comcast.com,4

In [30]:
df = pd.read_sql("SELECT * FROM artists", db, index_col='ArtistId')

In [31]:
df

                                                       Name
ArtistId
1                                                     AC/DC
2                                                    Accept
3                                                 Aerosmith
4                                         Alanis Morissette
5                                           Alice In Chains
...                                                     ...
271        Mela Tenenbaum, Pro Musica Prague & Richard Kapp
272                                  Emerson String Quartet
273       C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon...
274                                           Nash Ensemble
275                                   Philip Glass Ensemble

[275 rows x 1 columns]

In [32]:
df = pd.read_sql("SELECT * FROM customers LIMIT 15 ", db, index_col='CustomerId')

In [34]:
df.head()

,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
CustomerId,,,,,,,,,,,,
1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4

In [36]:
df = pd.read_sql("SELECT LastName, Address, Country  FROM customers", db)

In [37]:
df

        LastName                                   Address         Country
0      Gonçalves           Av. Brigadeiro Faria Lima, 2170          Brazil
1         Köhler                   Theodor-Heuss-Straße 34         Germany
2       Tremblay                         1498 rue Bélanger          Canada
3         Hansen                          Ullevålsveien 14          Norway
4    Wichterlová                             Klanova 9/506  Czech Republic
5           Holý                             Rilská 3174/6  Czech Republic
6         Gruber      Rotenturmstraße 4, 1010 Innere Stadt         Austria
7        Peeters                           Grétrystraat 63         Belgium
8        Nielsen                       Sønder Boulevard 51         Denmark
9        Martins                 Rua Dr. Falcão Filho, 155          Brazil
10         Rocha                        Av. Paulista, 2022          Brazil
11       Almeida                          Praça Pio X, 119          Brazil
12         Ramos                              Qe 7 Bloco G          Brazil
13       Philips                            8210 111 ST NW          Canada
14      Peterson                       700 W Pender Street          Canada
15        Harris                 1600 Amphitheatre Parkway             USA
16         Smith                           1 Microsoft Way             USA
17        Brooks                              627 Broadway             USA
18         Goyer                           1 Infinite Loop             USA
19        Miller                      541 Del Medio Avenue             USA
20         Chase                          801 W 4th Street             USA
21       Leacock                          120 S Orange Ave             USA
22        Gordon                           69 Salem Street             USA
23       Ralston                     162 E Superior Street             USA
24       Stevens                     319 N. Frances Street             USA
25    Cunningham                       2211 W Berry Street             USA
26          Gray                           1033 N Park Ave             USA
27       Barnett                               302 S 700 E             USA
28         Brown                    796 Dundas Street West          Canada
29       Francis                          230 Elgin Street          Canada
30          Silk                     194A Chain Lake Drive          Canada
31      Mitchell                        696 Osborne Street          Canada
32      Sullivan                            5112 48 Street          Canada
33     Fernandes                        Rua da Assunção 53        Portugal
34       Sampaio  Rua dos Campeões Europeus de Viena, 4350        Portugal
35     Schneider                        Tauentzienstraße 8         Germany
36    Zimmermann                          Berger Straße 10         Germany
37      Schröder                       Barbarossastraße 19         Germany
38       Bernard                             4, Rue Milton          France
39      Lefebvre                            8, Rue Hanovre          France
40        Dubois                       11, Place Bellecour          France
41        Girard                    9, Place Louis Barthou          France
42       Mercier                          68, Rue Jouvence          France
43    Hämäläinen                           Porthaninkatu 9         Finland
44        Kovács                         Erzsébet krt. 58.         Hungary
45      O'Reilly                          3 Chatham Street         Ireland
46       Mancini                    Via Degli Scipioni, 43           Italy
47  Van der Berg                     Lijnbaansgracht 120bg     Netherlands
48        Wójcik                              Ordynacka 10          Poland
49         Muñoz                        C/ San Bernardo 85           Spain
50     Johansson                               Celsiusg. 9          Sweden
51         Jones                         202 Hoxton Street  United Kingdom
52        Hughes                              113 Lupus St  United Kingdom
53        Murray                            110 Raeburn Pl  United Kingdom
54        Taylor                         421 Bourke Street       Australia
55     Gutiérrez                        307 Macacha Güemes       Argentina
56         Rojas                           Calle Lira, 198           Chile
57        Pareek                       12,Community Centre           India
58    Srivastava                         3,Raj Bhavan Road           India